### ISSUE TITLE
Actualización Sesión 2 - Scotiabank

### ISSUE THREAD

**Issue by ljubist** [Laboratoria/curso-HiPos#10]
Modo: producción
Actualización? : SI
Link de branch: https://github.com/Laboratoria/curso-HiPos/tree/scotiabank-HiPos+LBD
Link LMS: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/courses/curso-HiPos
Nombre de curso: Aprender Experimentando
Nombre de Empresa: Scotiabank
Sede: Lima
Fecha de inicio y termino (aplica cuando ya se aprobó el test):
Link de excel del cohort (aplica cuando ya se aprobó el test):
Se necesita reporte (aplica cuando ya se aprobó el test): NO

**Comment by FabianBravoA** [comment]
Listo
