### ISSUE TITLE
Update sesión 3

### ISSUE THREAD

**Issue by claudiaalf** [Laboratoria/curso-HiPos#11]
Modo: producción
Actualización? : SI
Link de branch: https://github.com/Laboratoria/curso-HiPos/tree/scotiabank-HiPos+LBD
Nombre de curso: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/courses/curso-HiPos
Nombre de Empresa: Scotiabank
Sede: Lima

**Comment by FabianBravoA** [comment]
Listo
