### ISSUE TITLE
Update Sesión 4 Banbif

### ISSUE THREAD

**Issue by ljubist** [Laboratoria/curso-HiPos#12]
Modo: ´producción
Actualización? : SI
Link de branch: https://github.com/Laboratoria/curso-HiPos/tree/scotiabank-HiPos+LBD
Link LMS: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/courses/curso-HiPos
Nombre de curso: Aprender Experimentando
Nombre de Empresa: Scotiabank
Sede: Lima

**Comment by FabianBravoA** [comment]
listo
