### ISSUE TITLE
Nuevo Curso en LMS - Scotiabank

### ISSUE THREAD

**Issue by claudiaalf** [Laboratoria/curso-HiPos#6]
Modo: TEST
Actualización : NO. Es un curso nuevo
Link de branch: https://github.com/Laboratoria/curso-HiPos/tree/scotiabank-HiPos+LBD
Nombre de curso: Learning by Dou¿ing
Nombre de Empresa: Scotiabank
Sede: Lima
Fecha de inicio y termino (aplica cuando ya se aprobó el test): 20/05 al 02/07

aún no tengo cohort, por lo que veámoslo primero como test, gracias!

**Comment by claudiaalf** [comment]
Hola @FabianBravoA ya me pasaron el cohort. 
Aquí la lista de estudiantes: https://docs.google.com/spreadsheets/d/1tdq7dTyyrnEaAfVeFSZ6Ju5KE0c4RjFatUXy4KcdI8M/edit#gid=0

La idea es que su correo sea el usuario, y el password sea el mismo usuario. Es decir, así:

user: claudia_alfaro@laboratoria.com
password: claudia_alfaro

Gracias!!

**Comment by FabianBravoA** [comment]
Listo
