### ISSUE TITLE
Reporte para Scotiabank

### ISSUE THREAD

**Issue by claudiaalf** [Laboratoria/curso-HiPos#7]
Hola @FabianBravoA tu ayuda para generar el reporte de ingresos para el curso de scotiabank:

- **Curso**: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/courses/curso-HiPos
- **Cohort**: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/users 
- **Contenido**: Ingreso a la plataforma e ingreso a las distintas secciones

Gracias!

**Comment by FabianBravoA** [comment]
Hecho
