### ISSUE TITLE
Update Sesión 2 Scotiabak

### ISSUE THREAD

**Issue by ljubist** [Laboratoria/curso-HiPos#9]
Modo: producción
Actualización? : SI
Link de branch: https://github.com/Laboratoria/curso-HiPos/tree/scotiabank-HiPos%2BLBD
Nombre de curso: Aprender Experimentando
Nombre de Empresa: Scotiabank
Link LMS: https://lms.laboratoria.la/cohorts/lim-2019-05-l4b-business-scotiabank-lbd1/courses/curso-HiPos
Se necesita reporte (aplica cuando ya se aprobó el test): NO

**Comment by FabianBravoA** [comment]
Hecho
